package com.anne.utils.localization

data class AppStrings(
    val desktopSwitcher: String,
    val settings: String,
    val virtualDesktopHotkeys: String,
    val hotkeyDescription: String,
    val status: String,
    val active: String,
    val inactive: String,
    val startAtStartupInTray: String,
    val showTrayIcon: String,
    val closeToTray: String,
    val shortcutBindings: String,
    val digitSequenceMode: String,
    val individualMode: String,
    val digitSequenceDescription: String,
    val individualDescription: String,
    val modifiers: String,
    val controlKey: String,
    val altKey: String,
    val shiftKey: String,
    val metaKey: String,
    val desktop: String,
    val recordShortcut: String,
    val pressShortcut: String,
    val cancel: String,
    val permissionRequired: String,
    val permissionMessage: String,
    val open: String,
    val exit: String
)

object AppLocalizations {
    private val italian = AppStrings(
        desktopSwitcher = "Desktop virtuali",
        settings = "Impostazioni",
        virtualDesktopHotkeys = "Scorciatoie desktop virtuali",
        hotkeyDescription = "Usa le scorciatoie configurate per cambiare desktop. Su Windows, aggiungi Maiusc per spostare la finestra attiva quando la scorciatoia non include gia Maiusc.",
        status = "Stato",
        active = "Attivo",
        inactive = "Non attivo",
        startAtStartupInTray = "Avvia con il sistema solo nell'area di notifica",
        showTrayIcon = "Mostra l'icona nell'area di notifica",
        closeToTray = "Alla chiusura, riduci nell'area di notifica",
        shortcutBindings = "Scorciatoie",
        digitSequenceMode = "Combinazione + numeri 0-9",
        individualMode = "Scorciatoie singole",
        digitSequenceDescription = "Scegli i modificatori da abbinare ai tasti 1-9 e 0. Il tasto 0 apre il desktop 10.",
        individualDescription = "Registra una combinazione diversa per ogni desktop.",
        modifiers = "Modificatori",
        controlKey = "Ctrl",
        altKey = "Alt",
        shiftKey = "Maiusc",
        metaKey = "Win/Cmd",
        desktop = "Desktop",
        recordShortcut = "Registra",
        pressShortcut = "Premi la nuova scorciatoia...",
        cancel = "Annulla",
        permissionRequired = "Autorizzazione necessaria",
        permissionMessage = "Impossibile abilitare l'accesso ai dispositivi di assistenza. Apri Impostazioni di Sistema -> Privacy e sicurezza -> Accessibilità e autorizza questa applicazione o il terminale.",
        open = "Apri",
        exit = "Esci"
    )

    private val english = AppStrings(
        desktopSwitcher = "Desktop Switcher",
        settings = "Settings",
        virtualDesktopHotkeys = "Virtual Desktop Hotkeys",
        hotkeyDescription = "Use the configured shortcuts to switch desktops. On Windows, add Shift to move the active window when the shortcut does not already include Shift.",
        status = "Status",
        active = "Active",
        inactive = "Inactive",
        startAtStartupInTray = "Start with the system in the tray only",
        showTrayIcon = "Show application tray icon",
        closeToTray = "Close application to the tray",
        shortcutBindings = "Shortcuts",
        digitSequenceMode = "Combination + digits 0-9",
        individualMode = "Individual shortcuts",
        digitSequenceDescription = "Choose modifiers to combine with keys 1-9 and 0. The 0 key opens desktop 10.",
        individualDescription = "Record a different key combination for each desktop.",
        modifiers = "Modifiers",
        controlKey = "Ctrl",
        altKey = "Alt",
        shiftKey = "Shift",
        metaKey = "Win/Cmd",
        desktop = "Desktop",
        recordShortcut = "Record",
        pressShortcut = "Press the new shortcut...",
        cancel = "Cancel",
        permissionRequired = "Permission Required",
        permissionMessage = "Failed to enable access for assistive devices. Open System Settings -> Privacy & Security -> Accessibility and grant permission to this application or your terminal.",
        open = "Open",
        exit = "Exit"
    )

    fun forLanguage(language: String): AppStrings =
        if (language.equals("it", ignoreCase = true)) italian else english
}
